### ISSUE TITLE
Issues with Permission from Discord?

### ISSUE THREAD

**Issue by colinfike** [MitchWeaver/Discline#19]
Hey couldn't find a way to contact the contributors outside of an issue.

Discord has been pretty outspoken about forbidding/banning users who use username/pass or user token to "selfbot" your account. I would assume using a custom client (that they also don't support) would count as self botting considering you are using the bot only API with a user account.

Have you ran into issues with this at all? I was working on my own CL client and have stopped seeing as it's a bannable offense.

**Comment by mitchweaver** [comment]
We haven't been contacted by any Discord staff, if they should choose to we are open ears.

For the record, Discline does not use any automated functions that would provide **any features outside of the official client**.

It is also stated in the readme that this topic is a grey area, and I/we cannot be held accountable should Discord take action against their accounts. We haven't had anyone be banned because of this, nor have I heard of it happening from use of other unofficial clients.

-----

[Here](https://github.com/discordapp/discord-api-docs/issues/69) is a quote from one of the Discord developers:

```
We're not interested in banning self bots. Some users use them to do cool things.
However, if your self bot does stupid stuff (like spams the API due to a bug in your code), 
we're much less forgiving than we would be if you were using a dedicated bot account. 
Like I said earlier, be smart and use a bot account. Self bots are not supported. 
Use them at your own risk (or demise!). Additionally, self bots should not act 
like actual bots, i.e. they shouldn't respond to other people's commands, join servers 
on your behalf, etc... And they definitely shouldn't do anything that's considered 
abuse of API for official bot accounts either.
```

Finally, please don't open public issues on such sensitive topics. This is a nice project, which I am happy to say many people enjoy using. I would hate to see it shut down.

**Comment by colinfike** [comment]
Not exactly shooting to get anything shut down though if a public issue does it then the days were probably numbered anyways.

https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots- 

They have definitely seemed to have taken a much harder stance on this lately which is why I reached out because I don't want to waste time developing/contributing on something that will just accounts banned. The posts from '06 were much more lenient from what I've seen.

**Comment by mitchweaver** [comment]
As I said, we have not been contacted and nor had any problems with accounts.

Should Discord wish to speak with us, may they do so.

Until then, I will consider this issue closed.
