### ISSUE TITLE
Audio support?

### ISSUE THREAD

**Issue by Catoptrix** [MitchWeaver/Discline#22]
Great program but:

Will it ever be possible to use it for gaming speech? Voice channel support?

Actually the main reason I use discord.

**Comment by RealProva** [comment]
And why exactly would you need command line support for audio?

**Comment by Epictek** [comment]
Why would you need command line support for text chat? Some users might want not want to use the bloated electron app.

As for voice support, The discord.py library does not support listening to voice chat currently. There is a PR (Rapptz/discord.py#1063 also see this issue Rapptz/discord.py#1094) but I'm not sure if it still works. There is also the rabbit hole of actually sending voice, discord.py supports sending audio but you would have to filter the voice for something more usable and also managing stuff like push to talk we would need to implement keybinds for different platforms because Linux and Windows use different APIs.

**Comment by Catoptrix** [comment]
I guess the purpose for this program is just for text. For Online Games you want to use your microphone for communication.

**Comment by Catoptrix** [comment]
Btw what is on the mainsite of this project? Im using brave browser on arch linux and I never had a problem, but when it is loading the discline code page my x server crashes :0

**Comment by Epictek** [comment]
Whst do you mean by mainsite? There is just the GitHub repo and the discord dev server (maybe join there to get more support?)

**Comment by Catoptrix** [comment]
I meant https://github.com/MitchWeaver/Discline. My browser crashes, there must be an element that is unusual there. Never had problems on twitch, youtube or other github sites. I will report that on the browser site.
Anyways, thx, will close this now. Peace
